name: KnetMiner-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - sparqlwrapper
  - scipy
  - base64
  - IPython
  - ipywidgets
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib